#ifndef PARSER_H
#define PARSER_H

#define RECORD_TYPE_INDEX    8

typedef enum {
	END_OF_FILE_RECORD,
	EXTENDED_SEGMENT_ADDRESS_RECORD,
	START_SEGMENT_ADDRESS_RECORD,
	EXTENDED_LINEAR_ADDRESS_RECORD,
	START_LINEAR_ADDRESS_RECORD,
	DATA_RECORD
}HEX_RECORD_TYPE;

HEX_RECORD_TYPE Parser_voidParseRecord(u8* Copy_u8BufData);

#endif // PARSER_H
